const state={items:[],selected:null,itemChart:null,cpiChart:null,config:{}};
const $=id=>document.getElementById(id);

async function api(path){const response=await fetch('/api'+path,{cache:'no-store'});if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return response.json()}
function money(value){return Number.isFinite(Number(value))?Number(value).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:3}):'–'}
function percent(value){const n=Number(value);if(!Number.isFinite(n))return '–';return `${n>0?'+':''}${n.toFixed(1)}%`}
function trendClass(value){const n=Number(value);return n>0?'up':n<0?'down':''}
function setStatus(ok,text){const status=document.querySelector('.status');status.classList.toggle('online',ok);status.classList.toggle('offline',!ok);$('status-text').textContent=text}

function applyConfig(config){state.config=config||{};if(config?.title){document.title=config.title;$('site-title').textContent=config.title}if(config?.accent)document.documentElement.style.setProperty('--accent',config.accent);if(config?.defaultTheme==='light'){document.documentElement.style.setProperty('--bg','#edf2f8');document.documentElement.style.setProperty('--panel','#ffffff');document.documentElement.style.setProperty('--panel2','#f8fafc');document.documentElement.style.setProperty('--text','#142033');document.documentElement.style.setProperty('--muted','#64748b');document.documentElement.style.setProperty('--border','#d7dfeb')}}

function renderItems(){const query=$('search').value.trim().toLowerCase();const items=state.items.filter(item=>!query||item.name?.toLowerCase().includes(query)||item.identifier?.toLowerCase().includes(query));const root=$('items');root.innerHTML='';if(!items.length){root.innerHTML='<div class="empty">No market items found.</div>';return}for(const item of items){const row=document.createElement('div');row.className='item'+(state.selected===item.identifier?' active':'');row.innerHTML=`<img src="/api/icons/${encodeURIComponent(item.identifier)}.png" alt="" onerror="this.style.opacity=.18"><div><div class="item-name">${escapeHtml(item.name||item.identifier)}</div><div class="item-sub"><span class="${trendClass(item.changePercent)}">${percent(item.changePercent)}</span> · ${item.operations??0} trades</div></div><div class="item-price">${money(item.price)}</div>`;row.addEventListener('click',()=>selectItem(item.identifier));root.appendChild(row)}}

function renderCategories(categories){$('metric-categories').textContent=categories.length;const root=$('categories');root.innerHTML=categories.length?'':'<div class="empty">No categories yet.</div>';for(const category of categories){const row=document.createElement('div');row.className='list-row';row.innerHTML=`<strong>${escapeHtml(category.name||category.identifier)}</strong><span class="${trendClass(category.changePercent)}">${percent(Number(category.changePercent)*100)}</span>`;root.appendChild(row)}}

function renderPortfolios(portfolios){const root=$('portfolios');root.innerHTML=portfolios.length?'':'<div class="empty">No portfolio data yet.</div>';$('metric-portfolio').textContent=portfolios.length?money(portfolios[0].value):'–';portfolios.forEach((portfolio,index)=>{const count=Object.values(portfolio.content||{}).reduce((a,b)=>a+Number(b||0),0);const row=document.createElement('div');row.className='list-row';row.innerHTML=`<strong>#${index+1} ${escapeHtml(portfolio.ownerName||'Unknown')}</strong><span>${money(portfolio.value)} · ${count} items</span>`;root.appendChild(row)})}

function renderPopular(item){$('popular').innerHTML=item?`🔥 Popular: <strong>${escapeHtml(item.name||item.identifier)}</strong> · ${money(item.price)}`:'No popular item yet.'}

function chartOptions(){return{responsive:true,maintainAspectRatio:false,animation:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#8e9ab3',maxTicksLimit:7},grid:{color:'rgba(100,120,150,.10)'}},y:{ticks:{color:'#8e9ab3'},grid:{color:'rgba(100,120,150,.10)'}}}}}
function drawChart(key,canvas,points,label){if(state[key])state[key].destroy();state[key]=new Chart($(canvas),{type:'line',data:{labels:points.map(p=>new Date(Number(p.time)*1000).toLocaleString()),datasets:[{label,data:points.map(p=>p.value),borderColor:state.config.accent||'#6E56CF',backgroundColor:'rgba(110,86,207,.15)',fill:true,tension:.18,pointRadius:0,borderWidth:2}]},options:chartOptions()})}

async function selectItem(identifier){state.selected=identifier;renderItems();const item=state.items.find(i=>i.identifier===identifier);$('selected-name').textContent=item?.name||identifier;$('selected-quote').textContent=item?`Price ${money(item.price)} · Buy ${money(item.buy)} · Sell ${money(item.sell)}`:'Loading…';try{const points=await api(`/charts/item/${encodeURIComponent(identifier)}`);drawChart('itemChart','item-chart',points,item?.name||identifier)}catch(error){console.error(error);drawChart('itemChart','item-chart',[],identifier)}}

async function refresh(){try{const [config,items,categories,portfolios,cpi]=await Promise.all([api('/config'),api('/items'),api('/categories'),api('/top-portfolios'),api('/charts/cpi')]);applyConfig(config);state.items=items||[];$('metric-items').textContent=state.items.length;renderItems();renderCategories(categories||[]);renderPortfolios(portfolios||[]);drawChart('cpiChart','cpi-chart',cpi||[],'CPI');try{renderPopular(await api('/popular-item'))}catch{renderPopular(null)}if(!state.selected&&state.items.length)await selectItem(state.items[0].identifier);setStatus(true,'Live')}catch(error){console.error('Nascraft web refresh failed',error);setStatus(false,'API unavailable')}}

function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}

document.addEventListener('DOMContentLoaded',()=>{$('search').addEventListener('input',renderItems);refresh();setInterval(refresh,5000)});
